In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\Class\Machine Learning\diabetes_binary_5050split_health_indicators_BRFSS2015.csv')

In [3]:
df

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [4]:
df.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [5]:
df.columns

Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [6]:
df.isnull().sum()

Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [7]:
df['Education']

0        6.0
1        6.0
2        6.0
3        6.0
4        5.0
        ...
70687    4.0
70688    3.0
70689    6.0
70690    2.0
70691    6.0
Name: Education, Length: 70692, dtype: float64

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = df.drop('Diabetes_binary', axis = 1)
scaler.fit(X)
X = scaler.transform(X)
X

array([[ 0.88020109, -1.05279808,  0.15927581, ..., -1.60723742,
         1.04856175,  1.05815996],
       [ 0.88020109,  0.94984976,  0.15927581, ...,  1.19768093,
         1.04856175,  1.05815996],
       [-1.13610402, -1.05279808,  0.15927581, ...,  1.54829572,
         1.04856175,  1.05815996],
       ...,
       [ 0.88020109,  0.94984976,  0.15927581, ...,  1.54829572,
         1.04856175, -0.78076781],
       [ 0.88020109,  0.94984976,  0.15927581, ...,  0.84706614,
        -2.83842972, -0.78076781],
       [ 0.88020109,  0.94984976,  0.15927581, ...,  0.14583655,
         1.04856175, -1.70023169]])

In [10]:
y = df['Diabetes_binary']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
X_train

array([[ 0.88020109,  0.94984976,  0.15927581, ...,  1.19768093,
         1.04856175,  0.13869608],
       [ 0.88020109,  0.94984976,  0.15927581, ...,  0.84706614,
        -0.89493398,  0.13869608],
       [-1.13610402,  0.94984976,  0.15927581, ...,  0.14583655,
         1.04856175,  1.05815996],
       ...,
       [ 0.88020109,  0.94984976,  0.15927581, ...,  0.84706614,
         1.04856175, -0.78076781],
       [ 0.88020109, -1.05279808,  0.15927581, ...,  0.49645134,
        -0.89493398,  0.13869608],
       [-1.13610402, -1.05279808,  0.15927581, ..., -2.308467  ,
         0.07681388,  0.59842802]])

In [15]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"% (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 23329 points : 6548

In [16]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB(force_alpha=True)
y_pred = clf.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"% (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 23329 points : 6247

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.73      0.73      0.73     11651
         1.0       0.73      0.73      0.73     11678

    accuracy                           0.73     23329
   macro avg       0.73      0.73      0.73     23329
weighted avg       0.73      0.73      0.73     23329